import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KDT01",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="w-full xl:w-4/5 h-screen mx-auto
                  flex flex-col justify-start items-center"
        >
          <Nav />
          <main
            className="w-full flex-grow flex flex-col items-center
                    overflow-y-auto"
          >
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
